[package]
name = "txgen"
version = "0.1.0"
edition = "2021"

[lib]
name = "txgen"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
#elements = { path = "/store/home/apoelstra/code/ElementsProject/rust-elements/2024-06--pegin-parse" }
# elements = { version = "0.25", default-features = false }
#simplicity = { package = "simplicity-lang", version = "0.2.0", default-features = false, features = [ "elements" ], path = "/store/home/apoelstra/code/BlockstreamResearch/rust-simplicity/2024-06--slab-inference" }
simplicity = { package = "simplicity-lang", version = "0.7.0", default-features = false, features = [ "bitcoin" ] }
# simplicity-sys = { package = "simplicity-sys", version = "0.3.0", default-features = false, features = [ "test-utils" ], git = "https://github.com/apoelstra/rust-simplicity", branch = "master" }
honggfuzz = { version = "0.5.56", optional = true, default-features = false }
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_transaction"
path = "src/fuzz_transaction.rs"
required-features = [ "honggfuzz" ]

#[[bin]]
#name = "fuzz_simplicity"
#path = "src/fuzz_simplicity.rs"
#required-features = [ "honggfuzz" ]

#[[bin]]
#name = "make_vectors"
#path = "src/make_vectors.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
